### ISSUE TITLE
[新機能]: 直剣スキル「空の構え」

### ISSUE THREAD

**Issue by Koryu25** [eryuLab/SkillMaster#175]
### 具体的な提案内容

敵の攻撃を寸前で回避しながら前方に移動する  
前方に突進する/0.2s～0.5s敵の攻撃を軽減/ノックバック無効

### 想定されるコード

N/A

**Comment by hirotask** [comment]
> 敵の攻撃を寸前
でなければ発動しないスキルで合ってますか？
