### ISSUE TITLE
[品質向上]: Messagerクラスの作成

### ISSUE THREAD

**Issue by hirotask** [eryuLab/SkillMaster#189]
### 改善案の具体的な内容

[このように](https://github.com/eryuLab/SkillMaster/blob/e4108726de8442e326d68367004c8f40ce369068/src/main/java/net/lifecity/mc/skillmaster/EventListener.kt#L47)メッセージを送信する処理において、タグ（[警告] みたいなやつ）を毎回書くのは面倒なので、クラス化したい。

### 想定されるコード
インスタンスを複数生成する必要はないと思われるので、objectで作ったほうがいいと思う。
```kotlin
object Messager {
    fun sendAlertMessage(player: Player, msg: String) {
        player.sendMessage("$WHITE[${RED}警告${WHITE}]: $msg")
    }
}
```

### 補足事項
ほかにも送信するメッセージのパターンがあれば、コメントしてください。

**Comment by Koryu25** [comment]
### タグの案
- お知らせ(運営からのアナウンス)
- デバッグ
- 警告
- エラー
- ログ(システム的な報告)
