### ISSUE TITLE
[新機能]: エフェクト処理の強化

### ISSUE THREAD

**Issue by Koryu25** [eryuLab/SkillMaster#199]
### 具体的な提案内容

- 半円や、弧を描く線のエフェクトメソッドを実装する。
- 上記の新エフェクトのアニメーションのエフェクトメソッドを実装
- アニメーション時の逆回転(始点と終点の入れ替え)を実装(これは既存のコードでもできますか？)

### 想定されるコード

N/A

**Comment by hirotask** [comment]
> アニメーション時の逆回転(始点と終点の入れ替え)を実装(これは既存のコードでもできますか？)
これに関しては、アニメーションするエフェクトを回転させて鏡面反転させれば良いのですが、それでもメソッドを実装した方がいいでしょうか？

**Comment by hirotask** [comment]
> 半円や、弧を描く線のエフェクトメソッドを実装する。

半円と弧の違いを明記してください。
（半円は弧の両端を繋ぐ直線がある図形、という意味かな？）

**Comment by Koryu25** [comment]
> > アニメーション時の逆回転(始点と終点の入れ替え)を実装(これは既存のコードでもできますか？)
> 
> これに関しては、アニメーションするエフェクトを回転させて鏡面反転させれば良いのですが、それでもメソッドを実装した方がいいでしょうか？
回転させる方法ありましたね。 新しく実装しなくて大丈夫です。

**Comment by Koryu25** [comment]
> > 半円や、弧を描く線のエフェクトメソッドを実装する。
> 
> 半円と弧の違いを明記してください。 （半円は弧の両端を繋ぐ直線がある図形、という意味かな？）

言葉のなかでは半円と弧の違いはありません。    
円の描画を途中で終了させることが条件です。
