### ISSUE TITLE
[新機能]: 攻撃者と攻撃対象の位置(角度)関係を判定する

### ISSUE THREAD

**Issue by Koryu25** [eryuLab/SkillMaster#236]
### 具体的な提案内容

スキル発動条件で攻撃者と攻撃対象の位置関係(角度)を判定する必要があります。  
[例](https://github.com/eryuLab/KoryuServerDocument/blob/main/%E6%B1%BA%E5%AE%9A%E4%BA%8B%E9%A0%85/%E3%82%B9%E3%82%AD%E3%83%AB/%E3%82%B9%E3%82%AD%E3%83%AB%E8%A9%B3%E7%B4%B0.md#%E7%99%BA%E5%8B%95%E6%9D%A1%E4%BB%B6%E8%A4%87%E6%95%B0%E3%81%AE%E3%83%91%E3%82%BF%E3%83%BC%E3%83%B3%E3%81%A7%E6%9B%B8%E3%81%8F-1)
実装をお願いします。  

### 想定されるコード

N/A

**Comment by hirotask** [comment]
角度はどこを０とした角度ですか？
プレイヤーの位置を０とした角度なら、３次元空間ではθとφの２種類あって（[ここ参照](https://ja.wikipedia.org/wiki/%E7%90%83%E9%9D%A2%E5%BA%A7%E6%A8%99%E7%B3%BB)）どちらを求めればいいですかね？

**Comment by Koryu25** [comment]
φを使います。  
プレイヤーの位置(水平線を向いたときが0度)から上、斜め上、横、斜め下、下の中のどの位置に対象がいるかを判定してください。

**Comment by hirotask** [comment]
θは今後使う可能性はないですか？

**Comment by hirotask** [comment]
もし使う可能性があるのであれば、どちらも求めるメソッドを作ってそれを使って「θを求めるメソッド」と「φを求めるメソッド」を作ります

**Comment by Koryu25** [comment]
Θはプレイヤーの視点が0度になるので似てますが、処理の意味が変わってくると思います。  
ちなみにΘは今後必ず使うことになります。

**Comment by Koryu25** [comment]
同時に実装できるならお願いします。

**Comment by hirotask** [comment]
ん、位置関係って視点方向に依存している？
位置って座標に依存しているから視点は関係ないんじゃない？

**Comment by hirotask** [comment]
たぶん、視点方向とプレイヤーの位置は別として扱ったほうがいいと思うよ。
混ぜると混乱する。

**Comment by hirotask** [comment]
（あと、おそらくプレイヤーAとプレイヤーBが同じ高さに立っている時θは90度だよ）

**Comment by Koryu25** [comment]
上から見た横方向はプレイヤーの視点方向で判定するパターンに限られます。
なのでさっきも言ったように処理の意味が変わってくるので今回は実装しなくてもいいです

**Comment by Koryu25** [comment]
えるどさんのことだから同時に実装できる可能性もあるので言っただけです。

**Comment by hirotask** [comment]
確認だけど、位置は向いてる方向に依存する？それとも依存しない？
座標だけに依存するなら、向いてる方向に関係なくプレイヤーAとプレイヤーBの座標をつないだベクトルのΘとΦを求めるし、
向いてる方向に依存するなら、プレイヤーAがプレイヤーBの方向を向いていた場合、向いてる方向のベクトルのΘとΦを求める

**Comment by hirotask** [comment]
（どちらを実装するかで意味合いが変わってくるので確認です）
