### ISSUE TITLE
[品質向上]: メッセージの出力を統一する

### ISSUE THREAD

**Issue by Koryu25** [eryuLab/SkillMaster#268]
### 改善案の具体的な内容

今まで使っていた処理を書き換える。
player.sendMessage()やskillUser.sendMessage()やBukkit.getLogger().log()を廃止し、すべてMessengerやLoggerで統一する

### 想定されるコード

N/A

**Comment by hirotask** [comment]
Messangerなのか、Messagerなのかどっちですか？

**Comment by hirotask** [comment]
英単語的には、`Messanger`はFacebookのアプリに使われている固有名詞で、`Messager`は固有名詞ではなく「メッセージを送る者」みたいな名詞だと思います。

**Comment by Koryu25** [comment]
Messangerのほうですね。  
あと、英単語的に正しいのは"a"じゃなくて"e"のMessengerだと思っていたんですがどうでしょう

**Comment by hirotask** [comment]
タイポです。直しました

**Comment by Koryu25** [comment]
MessengerじゃなくてMessagerなの！？

**Comment by hirotask** [comment]
今色々調べたら、`Messenger`も`Messager`も`Messeger`も単語としては存在しないみたいですね。申し訳ない。
~erがつくのは、動詞+erのみで、Messageは名詞の働きしかしないからみたいです。
なので、文法的に正しいのは`MessageSender`とかですかね・・・？

**Comment by Koryu25** [comment]
Messengerって調べたら普通に単語の意味出てきますけど、これは正式には正しくない英単語っていうことですか？  
私的には、正しくなくても、十分意味が伝わるほどに流通している単語なので、使ってもいいと思います。

**Comment by hirotask** [comment]
Messengerは株式会社Metaが運営しているアプリ名なので、企業が作った固有名詞になります。
なので、流通していると言ってもそれをそのまま使うのはよろしくないかな、と。

**Comment by Koryu25** [comment]
Messengerという単語は100%それを指しているわけではないと思います

**Comment by hirotask** [comment]
個人的にはMessengerといえば、チャットアプリであり「メッセージ送信機」とはなりません。一般的にもメッセンジャー（Messenger)はチャットアプリの印象だと思うのですが、こりゅーさんはどうでしょう？
仮に、チャットアプリの印象があるのであれば、それは「コメントなしでも理解できるコード」とは言えないのではないでしょうか

**Comment by Koryu25** [comment]
こりゅー的にはメッセージ送信者で認識してますね。  
それと、チャットアプリの印象があっても、SkillMasterのコード内にいきなり某チャットアプリの名前が出てきても、考えたらチャットアプリのことではないとわかると思います。

**Comment by hirotask** [comment]
では、`MessageSender`と`Messenger`どちらのほうが、より「メッセージ送信者」というクラスの機能を説明している英単語だと思いますか？

**Comment by Koryu25** [comment]
私の知見だと、どちらもおなじ意味に感じますね。

**Comment by hirotask** [comment]
個人的には`MessageSender`のほうがプログラミングにおいてはクラス名に多く使われている印象です

**Comment by hirotask** [comment]
個人的には包含している意味が少ないという点から２つの単語を見ると、`MessageSender`のほうが的確に物事を伝えられる気がします

**Comment by hirotask** [comment]
まあでも、こりゅーさんが`Messenger`という命名にこだわりがあるのであれば従います。**私は**`MessageSender`のほうが意味が限定されていてわかりやすい、というだけなので

**Comment by Koryu25** [comment]
意味はほぼ同じじゃないですか？  
私的にはMessengerでも十分伝わります。  
そのうえで、MessageSenderにするとよく使うにしてはクラス名が長いと思います

**Comment by hirotask** [comment]
こりゅーさん的には意味がほぼ同じであっても、他の人はそうではないということを理解してほしいです。
現に、私はMessengerと聞くとアプリの印象が強くチャット機能を提供するクラスかのように思えてしまいます。
したがって、クラス名が分かりづらいとか意味が複数あって限定的ではないというのも、一つのレビューとして受け取ってほしいです。
しかし
> 私的にはMessengerでも十分伝わります。
とこりゅーさんが思っていて、なおかつ
> MessageSenderにするとよく使うにしてはクラス名が長いと思います
とするのであれば、まあおそらくこだわりを持っていると思うのでMessengerで統一します。

ちなみに、クラス名は意味が伝わるなら長さは多少長くてもいいと思います（この**多少**は経験則に則りますが、だいたい単語の連結数が3語以上だったら長いと感じるかな）。
現に[MicrosoftのAzureでもMessageSenderというクラスは存在します](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.core.messagesender?view=azure-dotnet)し、[JavaのフレームワークのNablarch](https://fintan.jp/blog-category/nablarch/)でも
