### ISSUE TITLE
[品質向上]: PRのテンプレートを進化させる

### ISSUE THREAD

**Issue by hirotask** [eryuLab/SkillMaster#276]
### 改善案の具体的な内容

現在のPRのテンプレートは以下のようになっている。
```
### 具体的な実装方法または変更点
具体的な実装方法または変更点を記載

### 補足事項
補足事項を記載

### 関連するIssue
- close #Issue番号
```
以上のテンプレートに`テストして頂きたいこと`という項目を加え、これをテストケースとする。
こうすることで、テストしてほしいことをレビュワーに伝えることができる＆レビュワーによるテストが行われたか確認することが期待できる。

また、GUIの実装の際にはスクリーンショットもあったほうがわかりやすいため、スクリーンショットの項目も加えたい

### 想定されるコード
```
### 具体的な実装方法または変更点
具体的な実装方法または変更点を記載

### スクリーンショット

### テストして頂きたいこと
- [ ]  `/skill menu skill`と入力してスキル一覧画面が表示されるか
- [ ] 右クリックを押した時、スキル`〇〇`が発動するか

### 関連するIssue
- close #Issue番号
```

**Comment by Koryu25** [comment]
スクリーンショットはこんな書き方でもいいと思います
```md
- [ ] aiueo
![いまげ](image)
- [ ] hoge
```

あと、補足事項は除外であってますか？  
私的には今まであまり使われていなかったので除外でいいと思います。

**Comment by hirotask** [comment]
これは以下のようなことですかね？

- [ ] hogehoge
<img width="848" alt="スクリーンショット 2022-12-31 17 02 41" src="https://user-images.githubusercontent.com/24629484/210132193-8969ac99-1023-4fb0-9680-c91e317b69fb.png">
- [ ] hogehoge

こうしてしまうと、画像が多かった場合にチェックボックスが離れてしまって若干見にくいので、テストケースで画像を参照したいときは[内部リンクを使って](https://qiita.com/hennin/items/7ee58dd7d7c013a23be7)
```
- [ ] 〇〇をする（[ここ](#セクション)を参照）
```
というようにしたいという意図を込めて以上の書き方にしています。

補足事項はわざわざセクション分けしなくても`具体的な実装方法または変更点`にかけばいいかな・・・と思ったので除外しています

**Comment by hirotask** [comment]
今作ってみて思ったんですが、チェックボックスの間に画像挟めないっぽいですね・・・

**Comment by hirotask** [comment]
@Koryu25 
> チェックボックスの間に画像挟めないっぽい
とのことなので、
```
### 具体的な実装方法または変更点
具体的な実装方法または変更点を記載

### スクリーンショット

### テストして頂きたいこと
- [ ]  `/skill menu skill`と入力してスキル一覧画面が表示されるか
- [ ] 右クリックを押した時、スキル`〇〇`が発動するか

### 関連するIssue
- close #Issue番号
```
のテンプレートで作成してもいいですか？

**Comment by Koryu25** [comment]
確認だけど、スクショは絶対必要？省略してもいいときもあるよね。そのときは消すってことでいい？

**Comment by Koryu25** [comment]
了解です。私的にはOKです！
